export const DYNAMODB_MODEL = {
  jsonVersion: "1.0",
  targetPrefix: "DynamoDB_20120810",
  operations: {
    BatchExecuteStatement: ["Statements"],
    BatchGetItem: ["RequestItems"],
    BatchWriteItem: ["RequestItems"],
    CreateBackup: ["TableName", "BackupName"],
    CreateGlobalTable: ["GlobalTableName", "ReplicationGroup"],
    CreateTable: ["TableName"],
    DeleteBackup: ["BackupArn"],
    DeleteItem: ["TableName", "Key"],
    DeleteResourcePolicy: ["ResourceArn"],
    DeleteTable: ["TableName"],
    DescribeBackup: ["BackupArn"],
    DescribeContinuousBackups: ["TableName"],
    DescribeContributorInsights: ["TableName"],
    DescribeEndpoints: [],
    DescribeExport: ["ExportArn"],
    DescribeGlobalTable: ["GlobalTableName"],
    DescribeGlobalTableSettings: ["GlobalTableName"],
    DescribeImport: ["ImportArn"],
    DescribeKinesisStreamingDestination: ["TableName"],
    DescribeLimits: [],
    DescribeTable: ["TableName"],
    DescribeTableReplicaAutoScaling: ["TableName"],
    DescribeTimeToLive: ["TableName"],
    DisableKinesisStreamingDestination: ["TableName", "StreamArn"],
    EnableKinesisStreamingDestination: ["TableName", "StreamArn"],
    ExecuteStatement: ["Statement"],
    ExecuteTransaction: ["TransactStatements"],
    ExportTableToPointInTime: ["TableArn", "S3Bucket"],
    GetItem: ["TableName", "Key"],
    GetResourcePolicy: ["ResourceArn"],
    ImportTable: ["S3BucketSource", "InputFormat", "TableCreationParameters"],
    ListBackups: [],
    ListContributorInsights: [],
    ListExports: [],
    ListGlobalTables: [],
    ListImports: [],
    ListTables: [],
    ListTagsOfResource: ["ResourceArn"],
    PutItem: ["TableName", "Item"],
    PutResourcePolicy: ["ResourceArn", "Policy"],
    Query: ["TableName"],
    RestoreTableFromBackup: ["TargetTableName", "BackupArn"],
    RestoreTableToPointInTime: ["TargetTableName"],
    Scan: ["TableName"],
    TagResource: ["ResourceArn", "Tags"],
    TransactGetItems: ["TransactItems"],
    TransactWriteItems: ["TransactItems"],
    UntagResource: ["ResourceArn", "TagKeys"],
    UpdateContinuousBackups: ["TableName", "PointInTimeRecoverySpecification"],
    UpdateContributorInsights: ["TableName", "ContributorInsightsAction"],
    UpdateGlobalTable: ["GlobalTableName", "ReplicaUpdates"],
    UpdateGlobalTableSettings: ["GlobalTableName"],
    UpdateItem: ["TableName", "Key"],
    UpdateKinesisStreamingDestination: ["TableName", "StreamArn"],
    UpdateTable: ["TableName"],
    UpdateTableReplicaAutoScaling: ["TableName"],
    UpdateTimeToLive: ["TableName", "TimeToLiveSpecification"],
  },
} as const;

export type DynamoDbOperationName = keyof typeof DYNAMODB_MODEL.operations;

export const DYNAMODB_OPERATION_NAMES = Object.keys(DYNAMODB_MODEL.operations) as DynamoDbOperationName[];
